export const city = [
    {label: "Surat", value: "surat"},
    {label: "Ahmedabad", value: "ahmedabad"},
    {label: "Vadodara", value: "vadodara"},
    {label: "Rajkot", value: "rajkot"},
    {label: "Bhavnagar", value: "bhavnagar"},
    {label: "Jamnagar", value: "jamnagar"},
    {label: "Gandhinagar", value: "gandhinagar"},
    {label: "Junagadh", value: "junagadh"},
    {label: "Anand", value: "anand"},
    {label: "Navsari", value: "navsari"},
    {label: "Bharuch", value: "bharuch"},
    {label: "Vapi", value: "vapi"},
    {label: "Mehsana", value: "mehsana"},
    {label: "Morbi", value: "morbi"},
    {label: "Nadiad", value: "nadiad"},
    {label: "Valsad", value: "valsad"},
    {label: "Porbandar", value: "porbandar"},
    {label: "Patan", value: "patan"},
    {label: "Veraval", value: "veraval"}
];