services:
  room-atlas-api:
        depends_on:
            - db
            - redis-stack
        container_name: room-atlas
        image: ghcr.io/vedantjain8/room-atlas:latest
        restart: unless-stopped
        ports:
            - '3100:3100'
        environment:
            DB_HOST: localhost
            DB_PORT: 5432
            DB_DATABASE: roomatlas
            DB_USER: postgres
            DB_PASSWORD: root
            REDIS_URL: redis://localhost:6379
            EMAIL_MAIL: EMAIL_ID
            EMAIL_APP_PASSWORD: YOUR_EMAIL_APP_PASSWORD
            FRONTEND_URL: http://localhost:3000
            CLOUDINARY_CLOUD_NAME: CLOUDINARY_NAME
            CLOUDINARY_API_KEY: CLOUDINARY_API_KEY
            CLOUDINARY_API_SECRET: CLOUDINARY_API_SECRET_KEY
            CLOUDINARY_URL: cloudinary://CLOUDINARY_API_KEY:CLOUDINARY_API_SECRET_KEY@CLOUDINARY_NAME

  db:
    container_name: db
    user: 1000:1000
    image: postgres:alpine3.18
    restart: always
    ports:
      - 5432:5432
    volumes:
      - '/home/localhub/db/:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: CHANGETHIS
      POSTGRES_DATABASE: roomatlas
      PGDATA: /var/lib/postgresql/data/pgdata

  redis-stack:
    image: 'redis/redis-stack:latest'
    ports:
        - 8001:8001
        - 6379:6379
    container_name: redis-stack